### PR TITLE
lock components to windows

### LINKED ISSUE #88: Error when starting more than one terminal from terminal browser
Haven't dug in to it yet, but this keeps happening every time I open a new terminal beyond the first one:
```
E5108: Error executing lua: Vim:Can only call this function in an unmodified buffer
stack traceback:
	[C]: in function 'termopen'
	...start/nvim-ide/lua/ide/components/terminal/component.lua:91: in function 'new_term'
	...ua/ide/components/terminal/terminalbrowser/component.lua:103: in function 'new_term'
	...ua/ide/components/terminal/terminalbrowser/component.lua:49: in function <...ua/ide/components/terminal/terminalbrowser/component.lua:49>
```

This happens whether I press "n" in the terminal browser, or if I call `:Workspace TerminalBrowser New`, or both.

However, the terminal browser shows multiple terminals as though there _is_ more than one, and I can rename them individually, but they all bring up the same terminal if I hit enter on them.

Hoping someone can confirm if this is just a me thing, as this hasn't happened until recently.

Edit: I _did_ just update neovim to the latest nightly. Investigating.

Edit 2: Seems like it's rather not actually creating the new buffer or the `nvim_win_set_buf` isn't working correctly for the terminal in `new_term()`. Might be a me thing, not sure. I'll play with it tomorrow.

### PR DESCRIPTION
**Pull request by mrjones2014**
@ldelossa how about this? just specifically ignoring terminal components when locking.

Fixes #88

### CODE REVIEW

**Comment by ldelossa** [comment]
My concern is that this code may break any swapping of components. 

Does "Workspace SwapPanel" command still work? It may be OK since we swap the full panel in and out. 

Ignoring just the term component isnt probably good, since we will eventually want other stuff, like the log, to take over the bottom panel, and swap in and out between buffers. 

Maybe ignore the bottom panel all together for locking?

**Comment by mrjones2014** [comment]
Switching to checking if its the bottom panel instead of checking if term component works better, yeah. The `:Workspace SwapPanel` command works with this change.

**Comment by ldelossa** [comment]
Cool, comment is now outdated.

File: lua/ide/panels/panel.lua [hunk 1]
```diff
@@ -128,6 +128,29 @@ Panel.new = function(tab, position, components)
         -- refresh the component tracker since new component has been opened.
         self.component_tracker.refresh()
 
+        -- terminal takes up the bottom tab, and requires ability to switch
+        -- through multiple terminal buffers from the terminal explorer component
+        -- so do not "lock" the terminal component
```
Comment (ldelossa) [inline lua/ide/panels/panel.lua:133]: Outdated comment

**Comment by distek** [comment]
Works fine on my end.

**Review by ldelossa — APPROVED** [review]
